### ISSUE TITLE
Can't quick-reply to animated sticker message

### ISSUE THREAD

**Issue by zeroxxx2** [ivocass/whatsapp-quick-reply-button#1]
As topic title states. This is on Firefox.

Replying to other type of messages works fine.

**Comment by ivocass** [comment]
Hi @zeroxxx2. Sorry for the late reply. I wasn't notified of the issue. I was able to reproduce this bug and will fix it this weekend.

**Comment by ivocass** [comment]
Ok @zeroxxx2 good news. I found that the extension wasn't working due to WhatsApp changing its code (CSS classes).
I've uploaded a new version for Firefox and Chrome, which should be approved this week.
So keep an eye out for version 0.0.0.2 and please let me know if it's fixed for you.

**Comment by zeroxxx2** [comment]
I received the update just now on my Firefox and can confirm the bug has been fixed. Thank you for your effort.
