### ISSUE TITLE
Reply button won't show since Firefox version 83.0

### ISSUE THREAD

**Issue by floriensk** [ivocass/whatsapp-quick-reply-button#2]
The reply button does not appear next to the messages on [web.whatsapp.com](https://web.whatsapp.com) as usual. I encounter the problem since the last Firefox update to version 83.0.
I tried using the extension with all other extensions disabled but have come to the same conclusion.

I could not confirm the behaviour on other devices so it can well be something related to my Firefox settings.

**Comment by floriensk** [comment]
@ivocass I would be glad if you could look into this, whether you encounter the same behaviour.

**Comment by ivocass** [comment]
Hi @floriensk. I've updated Firefox to 83.0 (64-bit) and the extension works fine for me. I'll be on the lookout though.
In the meantime, you can double-click the message line to generate a reply (which is the native way of WhatsApp web for quick replying).

**Comment by floriensk** [comment]
Sure! Now I do realize, how useful the add-on actually is. 😏
I'm not sure then, what might cause the problem. I created a new, blank Firefox profile (based on default one), the only changes I made is adding your add-on and logging in to WhatsApp web, and the reply buttons didn't show up there either.
Keeping thumbs crossed that you can fix it!

**Comment by ivocass** [comment]
Ok @floriensk good news. I found that the extension wasn't working due to WhatsApp changing its code (CSS classes).
I've uploaded a new version for Firefox and Chrome, which should be approved this week.
So keep an eye out for version 0.0.0.2 and please let me know if it's fixed for you.

**Comment by floriensk** [comment]
Wonderful, it does work now!
Yeah it was likely that WhatsApp messed around with the CSS. I'm glad you could fix it!

**Comment by floriensk** [comment]
@ivocass I'm afraid, the problem is back... Since a few hours the buttons disappeared again.

**Comment by floriensk** [comment]
@ivocass Is there a chance that you can take a glance at it?
