### ISSUE TITLE
Code not working because Whatsapp has been updated

### ISSUE THREAD

**Issue by Marlendo** [ivocass/whatsapp-quick-reply-button#3]
i try using this extension but not working at my web whatsapp (Version 2.2110.12)

**Comment by floriensk** [comment]
This is the same issue as in #2, @ivocass could you please do a quick fix?

**Comment by ivocass** [comment]
hey @floriensk @Marlendo, sorry for the delay! I've just published the updated extension, which works with the latest WhatsApp.
the extension needs to be reviewed by Mozilla and Google, so keep an eye out for version 0.0.0.3, which includes the fix.

**Comment by floriensk** [comment]
Thanks @ivocass, sorry for the hassle!:)

**Comment by floriensk** [comment]
@ivocass at WhatsApp it seems to be quite brisk lately... they must have changed the CSS again, the button disappeared.

**Comment by ivocass** [comment]
Fixed! I updated it in a way that will make the extension less sensitive to WhatsApp's CSS changes now.
Keep an eye out for version 0.0.0.4; they have to review and approve the extension update at Mozilla and Google.

**Comment by floriensk** [comment]
Thanks so much! Will update it as soon as I can
